export const MAIN_SCENE = 'MAIN_SCENE';
export const AUTHORIZATION_SCENE = 'AUTHORIZATION_SCENE';

export const ADMINISTRATION_START_SCENE = 'ADMINISTRATION_START_SCENE';

export const EDIT_ADMINISTRATORS_SCENE = 'EDIT_ADMINISTRATORS_SCENE';

export const ADD_NEW_ADMINISTRATOR_SCENE = 'ADD_NEW_ADMINISTRATOR_SCENE';

export const REMOVE_ADMINISTRATOR_SCENE = 'REMOVE_ADMINISTRATOR_SCENE';
