import { ADD_NEW_PRODUCT_DESCRIPTION_KEYBOARD } from './message.const';

export const MAIN_SCENE = 'MAIN_SCENE';
export const AUTHORIZATION_SCENE = 'AUTHORIZATION_SCENE';

export const ADMINISTRATION_START_SCENE = 'ADMINISTRATION_START_SCENE';

export const EDIT_ADMINISTRATORS_SCENE = 'EDIT_ADMINISTRATORS_SCENE';

export const ADD_NEW_ADMINISTRATOR_SCENE = 'ADD_NEW_ADMINISTRATOR_SCENE';

export const REMOVE_ADMINISTRATOR_SCENE = 'REMOVE_ADMINISTRATOR_SCENE';

export const EDIT_PRODUCT_SCENE = 'EDIT_COTTAGES_SCENE';

export const ADD_NEW_PRODUCT_SCENE = 'ADD_NEW_PRODUCT_SCENE';

export const ADD_NEW_PRODUCT_DESCRIPTION_KEYBOARD_SCENE =
  'ADD_NEW_PRODUCT_DESCRIPTION_KEYBOARD_SCENE';

export const ADD_NEW_PRODUCT_PHOTOS_KEYBOARD_SCENE =
  'ADD_NEW_PRODUCT_PHOTOS_KEYBOARD_SCENE';

export const ADD_NEW_PRICE_GUESTS_KEYBOARD_SCENE =
  'ADD_NEW_PRICE_GUESTS_KEYBOARD_SCENE';
